// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: clear_projects.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const clearProjects = `-- name: ClearProjects :exec
UPDATE activities SET project_id = NULL WHERE project_id = $1
`

func (q *Queries) ClearProjects(ctx context.Context, projectID uuid.NullUUID) error {
	_, err := q.db.ExecContext(ctx, clearProjects, projectID)
	return err
}
