// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: delete_project.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = $1 AND user_id = $2
`

type DeleteProjectParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) error {
	_, err := q.db.ExecContext(ctx, deleteProject, arg.ID, arg.UserID)
	return err
}
