// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: detete_activity.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteActivity = `-- name: DeleteActivity :exec
DELETE FROM activities WHERE id = $1 AND user_id = $2
`

type DeleteActivityParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteActivity(ctx context.Context, arg DeleteActivityParams) error {
	_, err := q.db.ExecContext(ctx, deleteActivity, arg.ID, arg.UserID)
	return err
}
