// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: get_report_years_categories.sql

package database

import (
	"context"
)

const getReportYearsCategories = `-- name: GetReportYearsCategories :many
DROP FUNCTION get_activity_summary(uuid)
`

type GetReportYearsCategoriesRow struct {
}

func (q *Queries) GetReportYearsCategories(ctx context.Context) ([]GetReportYearsCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getReportYearsCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReportYearsCategoriesRow
	for rows.Next() {
		var i GetReportYearsCategoriesRow
		if err := rows.Scan(); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
