// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: get_report_years.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getReportYears = `-- name: GetReportYears :many
SELECT get_report_years FROM get_report_years($1)
`

// Test UUID 4f0081b0-2e30-47c7-836a-0bc06f7baaab
func (q *Queries) GetReportYears(ctx context.Context, inputUserID uuid.UUID) ([]interface{}, error) {
	rows, err := q.db.QueryContext(ctx, getReportYears, inputUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []interface{}
	for rows.Next() {
		var get_report_years interface{}
		if err := rows.Scan(&get_report_years); err != nil {
			return nil, err
		}
		items = append(items, get_report_years)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
