// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: get_report_months.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const getReportMonths = `-- name: GetReportMonths :many
SELECT 
    (r).return_month::TEXT as month,
    (r).return_year::INT as year,
    (r).avg_start_time as start_time,
    (r).category_data::JSONB as category_data,
    (r).project_data::JSONB as project_data 
FROM get_report_months($1, $2) AS r
`

type GetReportMonthsParams struct {
	InputUserID uuid.UUID
	InputYear   int32
}

type GetReportMonthsRow struct {
	Month        string
	Year         int32
	StartTime    interface{}
	CategoryData json.RawMessage
	ProjectData  json.RawMessage
}

// Test UUID 4f0081b0-2e30-47c7-836a-0bc06f7baaab
func (q *Queries) GetReportMonths(ctx context.Context, arg GetReportMonthsParams) ([]GetReportMonthsRow, error) {
	rows, err := q.db.QueryContext(ctx, getReportMonths, arg.InputUserID, arg.InputYear)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReportMonthsRow
	for rows.Next() {
		var i GetReportMonthsRow
		if err := rows.Scan(
			&i.Month,
			&i.Year,
			&i.StartTime,
			&i.CategoryData,
			&i.ProjectData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
