// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: get_report_weeks.sql

package database

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const getReportWeeks = `-- name: GetReportWeeks :many
SELECT 
    (r).return_week::DATE as week,
    (r).return_month::TEXT as month,
    (r).return_year::INT as year,
    (r).avg_start_time as start_time,
    (r).category_data::JSONB as category_data,
    (r).project_data::JSONB as project_data 
FROM get_report_weeks($1, $2, $3) AS r
`

type GetReportWeeksParams struct {
	InputUserID uuid.UUID
	InputYear   int32
	InputMonth  string
}

type GetReportWeeksRow struct {
	Week         time.Time
	Month        string
	Year         int32
	StartTime    interface{}
	CategoryData json.RawMessage
	ProjectData  json.RawMessage
}

// Test UUID 4f0081b0-2e30-47c7-836a-0bc06f7baaab
func (q *Queries) GetReportWeeks(ctx context.Context, arg GetReportWeeksParams) ([]GetReportWeeksRow, error) {
	rows, err := q.db.QueryContext(ctx, getReportWeeks, arg.InputUserID, arg.InputYear, arg.InputMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReportWeeksRow
	for rows.Next() {
		var i GetReportWeeksRow
		if err := rows.Scan(
			&i.Week,
			&i.Month,
			&i.Year,
			&i.StartTime,
			&i.CategoryData,
			&i.ProjectData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
