// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: get_report_years_categories1.sql

package database

import (
	"context"
)

const getReportYearsCategories1 = `-- name: GetReportYearsCategories1 :exec
DROP FUNCTION get_activity_summary(uuid)
`

func (q *Queries) GetReportYearsCategories1(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, getReportYearsCategories1)
	return err
}
