// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: get_report_years_categories3.sql

package database

import (
	"context"
)

const getReportYearsCategories3 = `-- name: GetReportYearsCategories3 :many
SELECT  FROM get_activity_summary($1)
`

type GetReportYearsCategories3Row struct {
}

// Test UUID 4f0081b0-2e30-47c7-836a-0bc06f7baaab
func (q *Queries) GetReportYearsCategories3(ctx context.Context, getActivitySummary interface{}) ([]GetReportYearsCategories3Row, error) {
	rows, err := q.db.QueryContext(ctx, getReportYearsCategories3, getActivitySummary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReportYearsCategories3Row
	for rows.Next() {
		var i GetReportYearsCategories3Row
		if err := rows.Scan(); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
