// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: get_report_years_categories2.sql

package database

import (
	"context"
)

const getReportYearsCategories2 = `-- name: GetReportYearsCategories2 :exec
CREATE OR REPLACE FUNCTION get_activity_summary(input_user_id UUID)
RETURNS TABLE(return_year INT, data JSONB) AS $$
BEGIN
    RETURN QUERY 
    SELECT 
        sub.year::INT AS return_year,  
        jsonb_object_agg(COALESCE(sub.category_id::TEXT, 'null'), sub.duration) 
    FROM (
        SELECT 
            EXTRACT(YEAR FROM a.start_time)::INT AS year,  
            a.category_id, 
            SUM(ROUND(EXTRACT(EPOCH FROM (a.end_time - a.start_time)) / 60)) AS duration
        FROM activities a 
        WHERE a.user_id = input_user_id  -- ✅ Do not filter out NULL values
        GROUP BY year, a.category_id
    ) sub
    GROUP BY sub.year
    ORDER BY sub.year DESC;
END;
$$ LANGUAGE plpgsql
`

func (q *Queries) GetReportYearsCategories2(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, getReportYearsCategories2)
	return err
}
