// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: update_project.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateProject = `-- name: UpdateProject :one

UPDATE projects SET project = $1 WHERE id = $2 AND user_id = $3
RETURNING id, created_at, updated_at, project, user_id
`

type UpdateProjectParams struct {
	Project string
	ID      uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject, arg.Project, arg.ID, arg.UserID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Project,
		&i.UserID,
	)
	return i, err
}
