// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: update_category.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateCategory = `-- name: UpdateCategory :one

UPDATE categories SET category = $1 WHERE id = $2 AND user_id = $3
RETURNING id, created_at, updated_at, category, user_id
`

type UpdateCategoryParams struct {
	Category string
	ID       uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, updateCategory, arg.Category, arg.ID, arg.UserID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.UserID,
	)
	return i, err
}
