// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: update_activity.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const updateActivity = `-- name: UpdateActivity :one
UPDATE activities SET
    activity = $1,
    start_time = $2,
    end_time = $3,
    updated_at = NOW(),
    project_id = $4,
    category_id = $5
WHERE id = $6
RETURNING id, created_at, updated_at, activity, start_time, end_time, user_id, project_id, category_id
`

type UpdateActivityParams struct {
	Activity   string
	StartTime  time.Time
	EndTime    time.Time
	ProjectID  uuid.NullUUID
	CategoryID uuid.NullUUID
	ID         uuid.UUID
}

func (q *Queries) UpdateActivity(ctx context.Context, arg UpdateActivityParams) (Activity, error) {
	row := q.db.QueryRowContext(ctx, updateActivity,
		arg.Activity,
		arg.StartTime,
		arg.EndTime,
		arg.ProjectID,
		arg.CategoryID,
		arg.ID,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Activity,
		&i.StartTime,
		&i.EndTime,
		&i.UserID,
		&i.ProjectID,
		&i.CategoryID,
	)
	return i, err
}
